# docker-compose.yml
version: "3"

services:
   frontend:
     build:
       dockerfile: Dockerfile
     volumes:
       - ./src:/app/src
       - /node_modules
     ports:
       - 50381:3000
     environment:
       - WATCHPACK_POLLING=true
       - REACT_APP_NAME=front

