# version: "3"

services:
  frontend:
    build: ./frontend_app/
    volumes:
      - ./src:/frontend_app/app/src
      - /frontend_app/node_modules
    ports:
      - 3000
    environment:
        REACT_APP_NAME: front
  
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./api.py"
    depends_on:
      - mysql
    ports:
      - 8000:5000
    environment:
      DB_PASS: ${DB_PASS}
      API_KEY: ${API_KEY}
      OMDB_API_KEY: ${OMDB_API_KEY}
     

  mysql:
    build: ./mysql/
    restart: always
    environment: 
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'